### ISSUE TITLE
ArrayOfObjectsFilterKeys null array crash

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#481]
crashes instantly in my project on startup. seems like when the array is empty in the first frame...or null or whatever 
i seem to fixed this issue by adding (highlight):

![image](https://user-images.githubusercontent.com/1138673/217852830-6f721b07-b37a-4ca3-8f4a-9543656e38e3.png)

Thats the crash report
TypeError: Cannot convert undefined or null to object
    at Function.keys ()
    at inArray.onChange.inKeysToKeep.onChange.inInvert.onChange.inSeperator.onChange (https://dev.cables.gl/api/ops/code?nc=258903:5965:36)
    at Port.forceChange (webpack-internal:///./src/core/core_port.js:365:29)
    at Port.set.Port.setValue (webpack-internal:///./src/core/core_port.js:300:26)
    at Link._setValue (webpack-internal:///./src/core/core_link.js:60:25)
    at Link.setValue (webpack-internal:///./src/core/core_link.js:30:31)
    at Port.set.Port.setValue (webpack-internal:///./src/core/core_port.js:321:165)
    at update (eval at getEvalFunction (https://dev.cables.gl/api/ops/code?nc=258903:16239:16), :51:17)
    at port.onChange (https://dev.cables.gl/api/ops/code?nc=258903:16389:29)
    at Port.forceChange (webpack-internal:///./src/core/core_port.js:365:29)

**Comment by pandrr** [comment]
thanks, fixed on dev.cables.gl
