### ISSUE TITLE
dev.cables editor crashing, when hovering StringCompose OP last free input with mouse in editor

### ISSUE THREAD

**Issue by tob-har** [cables-gl/cables_docs#567]
happening since 21.08. 11:04

Uncaught TypeError: str.match is not a function tooltips.js:112 
    at isMultilineString (tooltips.js:112:1)
    at Object.updateHoverToolTip (tooltips.js:171:1)
    at GlPort._onHover (glport.js:199:1)
    at EventTarget.emitEvent (eventtarget.js:133:1)
    at GlRect.mouseMove (glrect.js:293:1)
    at GlRect.mouseMove (glrect.js:314:1)
    at GlRectInstancer.mouseMove (glrectinstancer.js:582:1)
    at GlPatch.mouseMove (glpatch.js:1089:1)
    at GlPatch.render (glpatch.js:961:1)
    at GlUiCanvas.render (gluicanvas.js:255:1)

**Comment by pandrr** [comment]
hopefully fixed, saw the automatic generated report

**Comment by tob-har** [comment]
yes, fixed.
thanks!
